In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import sklearn

TensorFlow 2.x selected.


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
X_train = np.load("/content/drive/My Drive/X_shuffled_0.npy").tolist()
Y_train = np.load("/content/drive/My Drive/Y_shuffled_0.npy").tolist()

In [0]:
X_train = np.array(X_train)

In [0]:
Y_train = np.array(Y_train)

In [5]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
Y_train = Y_train.reshape(-1,1)
print(Y_train)
enc.fit(Y_train)
Y_train = enc.transform(Y_train).toarray()
print(Y_train)

[['zero']
 ['left']
 ['right']
 ...
 ['happy']
 ['eight']
 ['dog']]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
X_train.shape, Y_train.shape

((1121, 22050), (1121, 30))

In [7]:
X_train = X_train.reshape(X_train.shape[0],X_train.shape[1],1)
print(X_train.shape)

(1121, 22050, 1)


In [0]:
input_shape = (X_train.shape[1],1)

In [13]:
from tensorflow.keras.layers import LSTM,Dense,ConvLSTM2D,MaxPool1D,Flatten,Dropout,Input,Conv1D

model = tf.keras.models.Sequential()
model.add(Conv1D(16,activation='relu',input_shape=input_shape,kernel_size=(10)))
model.add(MaxPool1D())
model.add(Dropout(0.2))
model.add(Conv1D(32,activation='relu',kernel_size=(10)))
model.add(MaxPool1D())
model.add(Dropout(0.2))
model.add(Conv1D(16,activation='relu',kernel_size=(10)))
model.add(MaxPool1D())
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(30,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,Y_train,batch_size=64,epochs=10)

model.save("model.h5")

Train on 1121 samples
Epoch 1/10
1121/1121 [==============================] - 22s 20ms/sample - loss: 3.4008 - accuracy: 0.0375
Epoch 2/10
1121/1121 [==============================] - 22s 19ms/sample - loss: 3.3467 - accuracy: 0.0517
Epoch 3/10
1121/1121 [==============================] - 22s 19ms/sample - loss: 3.1337 - accuracy: 0.1347
Epoch 4/10
1121/1121 [==============================] - 22s 20ms/sample - loss: 2.4098 - accuracy: 0.3577
Epoch 5/10
1121/1121 [==============================] - 22s 20ms/sample - loss: 1.4403 - accuracy: 0.6191
Epoch 6/10
1121/1121 [==============================] - 22s 20ms/sample - loss: 0.8139 - accuracy: 0.7904
Epoch 7/10
1121/1121 [==============================] - 22s 19ms/sample - loss: 0.5499 - accuracy: 0.8751
Epoch 8/10
1121/1121 [==============================] - 22s 20ms/sample - loss: 0.4267 - accuracy: 0.9135
Epoch 9/10
1121/1121 [==============================] - 22s 20ms/sample - loss: 0.3654 - accuracy: 0.9135
Epoch 10/10
1121/1121 [=

In [0]:
list_of_classes = ['bed', 'bird', 'cat', 'dog', 'down', 'eight', 'five', 'four', 'go', 'happy', 'house', 'left', 'marvin', 'nine', 'no', 'off', 'on', 'one', 'right', 'seven', 'sheila', 'six', 'stop', 'three', 'tree', 'two', 'up', 'wow', 'yes', 'zero']

In [21]:
prediction = model.predict(X_train)
print(list_of_classes[np.argmax(Y_train[0])])
print(list_of_classes[np.argmax(prediction[0])])

zero
zero
